- README.md
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
> docs: README.md refactoring

- linkup/src/main/java/com/learningcrew/linkup/place/query/dto/response/PlaceDetailResponse.java
- linkup/src/main/java/com/learningcrew/linkup/place/query/dto/response/PlaceReviewResponse.java
- linkup/src/main/resources/mappers/place/PlaceMapper.xml
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
> refactor 장소 상세조회에서 장소 리뷰 조회 추가

- linkup/src/main/java/com/learningcrew/linkup/linker/query/controller/FriendQueryController.java
- linkup/src/main/java/com/learningcrew/linkup/linker/query/dto/query/FriendRequestStatusDTO.java
- linkup/src/main/java/com/learningcrew/linkup/linker/query/dto/response/FriendInfoResponse.java
- linkup/src/main/java/com/learningcrew/linkup/linker/query/dto/response/FriendRequestResponse.java
- linkup/src/main/java/com/learningcrew/linkup/linker/query/mapper/FriendMapper.java
- linkup/src/main/java/com/learningcrew/linkup/linker/query/service/FriendQueryServiceImpl.java
- linkup/src/main/resources/mappers/linker/FriendMapper.xml
Closes #134 
Closes #133 
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
> [Feat] 친구 목록 및 친구 요청 신청 조회 기능 구현

- linkup/src/main/java/com/learningcrew/linkup/exception/ErrorCode.java
- linkup/src/main/java/com/learningcrew/linkup/linker/command/application/controller/FriendCommandController.java
- linkup/src/main/java/com/learningcrew/linkup/linker/command/application/service/FriendCommandServiceImpl.java
- linkup/src/main/java/com/learningcrew/linkup/linker/command/domain/aggregate/Friend.java
- linkup/src/main/java/com/learningcrew/linkup/linker/command/domain/aggregate/FriendId.java
- linkup/src/main/java/com/learningcrew/linkup/linker/command/domain/repository/FriendRepository.java
- linkup/src/main/java/com/learningcrew/linkup/linker/query/controller/FriendQueryController.java
- linkup/src/main/java/com/learningcrew/linkup/linker/query/dto/query/FriendRequestStatusDTO.java
- linkup/src/main/java/com/learningcrew/linkup/linker/query/dto/response/FriendInfoResponse.java
- linkup/src/main/java/com/learningcrew/linkup/linker/query/dto/response/FriendRequestResponse.java
- linkup/src/main/java/com/learningcrew/linkup/linker/query/mapper/FriendMapper.java
- linkup/src/main/java/com/learningcrew/linkup/linker/query/service/FriendQueryServiceImpl.java
- linkup/src/main/resources/mappers/linker/FriendMapper.xml
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
> [Feat] 친구 요청 수락 기능 구현

- linkup/src/main/java/com/learningcrew/linkup/exception/ErrorCode.java
- linkup/src/main/java/com/learningcrew/linkup/linker/command/application/controller/FriendCommandController.java
- linkup/src/main/java/com/learningcrew/linkup/linker/command/application/service/FriendCommandService.java
- linkup/src/main/java/com/learningcrew/linkup/linker/command/application/service/FriendCommandServiceImpl.java
- linkup/src/main/java/com/learningcrew/linkup/linker/command/domain/aggregate/Friend.java
- linkup/src/main/java/com/learningcrew/linkup/linker/command/domain/aggregate/FriendId.java
- linkup/src/main/java/com/learningcrew/linkup/linker/command/domain/repository/FriendRepository.java
- linkup/src/main/java/com/learningcrew/linkup/linker/query/controller/FriendQueryController.java
- linkup/src/main/java/com/learningcrew/linkup/linker/query/dto/query/FriendRequestStatusDTO.java
- linkup/src/main/java/com/learningcrew/linkup/linker/query/dto/response/FriendInfoResponse.java
- linkup/src/main/java/com/learningcrew/linkup/linker/query/dto/response/FriendRequestResponse.java
- linkup/src/main/java/com/learningcrew/linkup/linker/query/mapper/FriendMapper.java
- linkup/src/main/java/com/learningcrew/linkup/linker/query/service/FriendQueryServiceImpl.java
- linkup/src/main/resources/mappers/linker/FriendMapper.xml
Closes #132
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
> [Feat] 친구 거절 및 삭제 기능 구현

- linkup/src/main/resources/mappers/meeting/MeetingMapper.xml
- merge conflict 해결 과정에서 order by가 2번 들어가서 생긴 문제
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
> hotfix: merge 후 조회가 안되던 문제 수정

- linkup/src/main/java/com/learningcrew/linkup/exception/ErrorCode.java
merge 순서 꼬여서 줄 삭제됨
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
> hotfix: errorcode 누락 문제 해결

- linkup/src/main/java/com/learningcrew/linkup/place/command/application/controller/FavoriteCommandController.java
- linkup/src/main/java/com/learningcrew/linkup/place/command/application/controller/PlaceCommandController.java
- linkup/src/main/java/com/learningcrew/linkup/place/command/application/service/FavoriteCommandService.java
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
> feat 즐겨찾기 삭제 구현

- linkup/src/main/java/com/learningcrew/linkup/place/query/dto/response/PlaceDto.java
- linkup/src/main/java/com/learningcrew/linkup/place/query/mapper/PlaceMapper.java
- linkup/src/main/java/com/learningcrew/linkup/place/query/service/PlaceQueryService.java
- linkup/src/main/resources/mappers/place/PlaceMapper.xml
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
> feat: 장소 세부조회 기능 구현

- linkup/src/main/java/com/learningcrew/linkup/meeting/command/application/controller/MeetingCommandController.java
- linkup/src/main/java/com/learningcrew/linkup/meeting/command/application/service/MeetingCommandService.java
- linkup/src/main/java/com/learningcrew/linkup/meeting/command/application/service/MeetingParticipationCommandService.java
- linkup/src/main/java/com/learningcrew/linkup/place/command/application/service/ReservationCommandService.java
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
> Refactor 예약 거절 수정

- linkup/src/main/java/com/learningcrew/linkup/meeting/command/application/service/MeetingCommandService.java
- linkup/src/main/java/com/learningcrew/linkup/meeting/command/application/service/MeetingParticipationCommandService.java
- linkup/src/main/java/com/learningcrew/linkup/notification/command/application/helper/PointNotificationHelper.java
---
📌 개요
🔨 주요 변경 사항
모임 개설 및 참가 신청 시 포인트 차감 알림 발송 기능 추가
✅ 리뷰 요청 사항
> [feat] 모임 개설 및 참가 신청 승인 시 포인트 차감 알림 발송 기능 추가

- linkup/src/main/java/com/learningcrew/linkup/meeting/command/application/service/MeetingCommandService.java
- linkup/src/main/java/com/learningcrew/linkup/meeting/command/application/service/MeetingParticipationCommandService.java
- linkup/src/main/java/com/learningcrew/linkup/meeting/query/dto/response/MeetingParticipationDTO.java
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
> feat 개설자 모임 폭파 수정 필요

- linkup/src/main/java/com/learningcrew/linkup/meeting/command/application/controller/MeetingCommandController.java
- linkup/src/main/java/com/learningcrew/linkup/meeting/command/application/service/MeetingCommandService.java
- linkup/src/main/java/com/learningcrew/linkup/meeting/command/application/service/MeetingParticipationCommandService.java
- linkup/src/main/java/com/learningcrew/linkup/meeting/command/application/service/MeetingScheduler.java
- linkup/src/main/java/com/learningcrew/linkup/meeting/command/domain/repository/MeetingRepository.java
- linkup/src/main/java/com/learningcrew/linkup/meeting/query/service/MeetingParticipationQueryService.java
- linkup/src/main/java/com/learningcrew/linkup/point/command/application/service/PointCommandService.java
- linkup/src/main/resources/mappers/meeting/MeetingParticipationMapper.xml
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
> [feat] 모임 취소/개설 시 사업자 point 변환 완료 

- linkup/src/main/java/com/learningcrew/linkup/config/SecurityConfig.java
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
> refactor: 미팅쪽 권한 변경

- linkup/src/main/resources/mappers/community/CommentMapper.xml
- linkup/src/main/resources/mappers/community/PostMapper.xml
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
> feat: 커뮤니티 XML 파일 추가

- README.md
- assets/ddl/linkip_DDL.sql
- linkup/src/main/java/com/learningcrew/linkup/meeting/query/controller/AdminMeetingManageController.java
- linkup/src/main/java/com/learningcrew/linkup/place/command/application/controller/PlaceReviewCommandController.java
- linkup/src/main/java/com/learningcrew/linkup/point/command/application/controller/PointCommandController.java
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
> docs: update

- linkup/src/main/java/com/learningcrew/linkup/meeting/command/application/service/MeetingCommandServiceImpl.java
- linkup/src/main/java/com/learningcrew/linkup/meeting/command/application/service/MeetingParticipationCommandServiceImpl.java
- linkup/src/main/java/com/learningcrew/linkup/meeting/command/domain/repository/MeetingRepository.java
- linkup/src/main/java/com/learningcrew/linkup/point/command/application/service/PointCommandService.java
---
📌 개요
🔨 주요 변경 사항
1. 중복 시간 방지 
2. 브레이크 타임 추가 버전 브레이크 타임 예약 방지
3. 장소 ID 못찾는 경우 예외 처리 추가
✅ 리뷰 요청 사항
> Refactor / 모임 관련 예외처리 추가

- linkup/src/main/java/com/learningcrew/linkup/meeting/command/application/controller/ReservationCommandController.java
- linkup/src/main/java/com/learningcrew/linkup/place/command/application/service/ReservationCommandService.java
- linkup/src/main/java/com/learningcrew/linkup/place/command/domain/aggregate/entity/Reservation.java
---
📌 개요
🔨 주요 변경 사항
1. 외부 예약 등록 구현
2. 외부 예약 삭제 구현
3. meetingId가 null인 상황이 외부 예약입니다.
✅ 리뷰 요청 사항
> Feat / 외부 예약 등록 , 삭제 구현 완료

- linkupUser/src/main/java/com/learningcrew/linkupuser/command/application/service/AuthCommandServiceImpl.java
- linkupUser/src/main/java/com/learningcrew/linkupuser/common/util/SecurityUtils.java
- linkupUser/src/main/java/com/learningcrew/linkupuser/config/SecurityConfig.java
- linkupUser/src/main/java/com/learningcrew/linkupuser/query/controller/UserMypageQueryController.java
- linkupUser/src/main/java/com/learningcrew/linkupuser/query/dto/constants/RoleType.java
- linkupUser/src/main/java/com/learningcrew/linkupuser/query/dto/response/BusinessMypageResponse.java
- linkupUser/src/main/java/com/learningcrew/linkupuser/query/dto/response/UserMypageResponse.java
- linkupUser/src/main/java/com/learningcrew/linkupuser/query/mapper/UserMapper.java
- linkupUser/src/main/java/com/learningcrew/linkupuser/query/service/UserQueryService.java
- linkupUser/src/main/java/com/learningcrew/linkupuser/query/service/UserQueryServiceImpl.java
- linkupUser/src/main/resources/application-dev.yaml
- linkupUser/src/main/resources/mappers/linker/UserMapper.xml
- linkup_Gateway/src/main/resources/application.yaml
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
> Refactor: linkup user 마이페이지 조회 api 추가

- linkup/src/main/java/com/learningcrew/linkup/meeting/query/dto/response/MeetingDTO.java
- linkup/src/main/java/com/learningcrew/linkup/meeting/query/dto/response/MeetingSummaryDTO.java
- linkup/src/main/java/com/learningcrew/linkup/meeting/query/service/MeetingService.java
- linkup/src/main/resources/mappers/meeting/MeetingMapper.xml
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
> fix: placeId로부터 place 조회

- linkup/src/main/java/com/learningcrew/linkup/common/util/StringToYearMonthConverter.java
- linkup/src/main/java/com/learningcrew/linkup/config/SecurityConfig.java
- linkup/src/main/java/com/learningcrew/linkup/config/WebConfig.java
- linkup/src/main/java/com/learningcrew/linkup/point/query/controller/PointQueryController.java
- linkup/src/main/java/com/learningcrew/linkup/point/query/dto/query/AccountSearchCondition.java
- linkup/src/main/java/com/learningcrew/linkup/point/query/dto/query/SettlementTransactionSearchCondition.java
- linkup/src/main/java/com/learningcrew/linkup/point/query/dto/response/AccountHistory.java
- linkup/src/main/java/com/learningcrew/linkup/point/query/dto/response/SettlementHistory.java
- linkup/src/main/java/com/learningcrew/linkup/point/query/mapper/AccountMapper.java
- linkup/src/main/java/com/learningcrew/linkup/point/query/mapper/PointTransactionMapper.java
- linkup/src/main/java/com/learningcrew/linkup/point/query/service/PointQueryService.java
- linkup/src/main/java/com/learningcrew/linkup/point/query/service/PointQueryServiceImpl.java
- linkup/src/main/resources/mappers/point/PointTransactionMapper.xml
- linkup/src/main/resources/mappers/point/accountMapper.xml
- linkupUser/src/main/java/com/learningcrew/linkupuser/command/application/service/AccountCommandServiceImpl.java
- linkupUser/src/main/java/com/learningcrew/linkupuser/command/domain/service/TokenDomainServiceImpl.java
- linkupUser/src/main/java/com/learningcrew/linkupuser/command/domain/service/UserValidatorServiceImpl.java
- linkupUser/src/main/java/com/learningcrew/linkupuser/exception/ErrorCode.java
- linkupUser/src/main/java/com/learningcrew/linkupuser/query/controller/UserMypageQueryController.java
- linkupUser/src/main/java/com/learningcrew/linkupuser/query/dto/query/MeetingHistorySearchCondition.java
- linkupUser/src/main/java/com/learningcrew/linkupuser/query/dto/response/MeetingHistoryResponse.java
- linkupUser/src/main/java/com/learningcrew/linkupuser/query/mapper/UserMapper.java
- linkupUser/src/main/java/com/learningcrew/linkupuser/query/service/MeetingQueryService.java
- linkupUser/src/main/java/com/learningcrew/linkupuser/query/service/MeetingQueryServiceImpl.java
- linkupUser/src/main/resources/mappers/linker/UserMapper.xml
- linkupUser/src/main/resources/templates/email/password-reset.html
- linkup_Gateway/src/main/java/com/learningcrew/gateway/jwt/GatewayJwtTokenProvider.java
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
> refactor: 회원 쪽 코드 수정

- linkup/src/main/java/com/learningcrew/linkup/meeting/query/dto/response/MeetingDTO.java
- linkup/src/main/java/com/learningcrew/linkup/meeting/query/dto/response/MeetingSummaryDTO.java
- linkup/src/main/java/com/learningcrew/linkup/meeting/query/mapper/MeetingMapper.java
- linkup/src/main/java/com/learningcrew/linkup/meeting/query/service/MeetingService.java
- linkup/src/main/resources/mappers/meeting/MeetingMapper.xml
- linkupUser/src/main/java/com/learningcrew/linkupuser/config/SecurityConfig.java
- linkupUser/src/main/java/com/learningcrew/linkupuser/query/controller/UserMypageQueryController.java
- 모임별 참가자 수, 모임별 찜 등록자 수 표시 구현
- feat/meeting 브랜치 기준, 엔드포인트 중복 문제 수정 ~(하나 주석처리)~
- 오타로 추정되는 엔드포인트 "/" 추가
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
~담당자 분께서 어느 엔드포인트가 올바른지 확인한 후 main에 반영 부탁드립니다.~
엔드포인트 카톡 논의 내용대로 수정 완료
> feat: 모임 조회, 모임 상세 조회 보완

- linkup/src/main/java/com/learningcrew/linkup/config/SecurityConfig.java
- linkup/src/main/java/com/learningcrew/linkup/config/SwaggerConfig.java
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
> feat: 엔드포인트 오류 수정 및 스웨거 url 변경

- linkup/src/main/java/com/learningcrew/linkup/meeting/query/dto/response/MeetingSummaryDTO.java
- linkup/src/main/java/com/learningcrew/linkup/meeting/query/service/MeetingService.java
참가비를 목록에서 띄울 수 있도록 수정
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
> refactor: 모임 목록 조회 수정

- linkup/src/main/java/com/learningcrew/linkup/report/command/application/service/PenaltyAdminServiceImpl.java
- linkup/src/main/java/com/learningcrew/linkup/report/command/application/service/ReportAdminServiceImpl.java
- linkup/src/main/java/com/learningcrew/linkup/report/command/domain/repository/ReportRepository.java
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
> refactor: 신고 및 제재 로직 개선
